<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database with complete production initial data.
     */
    public function run(): void
    {
        // 1. Units
        $units = [
            [
                'id'         => 1,
                'nama_unit'  => 'Unit Kopi Polinela',
                'slug'       => 'unit-kopi-polinela',
                'deskripsi'  => 'Unit usaha dan Teaching Factory pengolahan biji kopi robusta dan arabika unggulan dari kebun riset Polinela.',
                'logo'       => 'unit-kopi.png',
                'pj_nama'    => 'Ir. Hendra Saputra, M.T.A.',
                'kontak'     => '0812-3456-7801',
                'lokasi'     => 'Gedung Tefa Pengolahan Hasil Kopi Polinela',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 2,
                'nama_unit'  => 'Unit Kakao & Cokelat Polinela',
                'slug'       => 'unit-kakao-polinela',
                'deskripsi'  => 'Unit pengolahan fermentasi biji kakao premium, cokelat batang artesanal, dan kakao nibs bermutu tinggi.',
                'logo'       => 'unit-kakao.png',
                'pj_nama'    => 'Dr. Maya Kartika, S.P., M.Si.',
                'kontak'     => '0812-3456-7802',
                'lokasi'     => 'Laboratorium Terpadu Kakao Polinela',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 3,
                'nama_unit'  => 'Unit Lada & Rempah Lampung',
                'slug'       => 'unit-lada-rempah',
                'deskripsi'  => 'Unit budidaya dan pemrosesan lada hitam (Lampung black pepper) dan rempah khas Lampung berstandar ekspor.',
                'logo'       => 'unit-lada.png',
                'pj_nama'    => 'Bambang Kusumo, S.St., M.Tr.P.',
                'kontak'     => '0812-3456-7803',
                'lokasi'     => 'Kebun Percobaan Rempah Polinela',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 4,
                'nama_unit'  => 'Unit Olahan & Atsiri Tefa',
                'slug'       => 'unit-olahan-atsiri',
                'deskripsi'  => 'Unit penyulingan minyak atsiri serai wangi, pupuk organik hayati, dan produk olahan hortikultura kampus.',
                'logo'       => 'unit-atsiri.png',
                'pj_nama'    => 'Nurul Hidayati, S.P., M.Sc.',
                'kontak'     => '0812-3456-7804',
                'lokasi'     => 'Pusat Bio-Industri & Tefa Hortikultura Polinela',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('units')->upsert($units, ['id']);

        // 2. Users (Semua role dari Superadmin sampai Konsumen)
        $users = [
            [
                'id'         => 1,
                'nama'       => 'Super Administrator',
                'email'      => 'admin@polinela.ac.id',
                'password'   => Hash::make('admin123'),
                'no_hp'      => '081234567890',
                'role'       => 'superadmin',
                'foto'       => 'default-avatar.png',
                'unit_id'    => null,
                'alamat'     => 'Gedung Rektorat Polinela, Bandar Lampung',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 2,
                'nama'       => 'Admin Unit Kopi Polinela',
                'email'      => 'adminkopi@polinela.ac.id',
                'password'   => Hash::make('admin123'),
                'no_hp'      => '081234567891',
                'role'       => 'admin_unit',
                'foto'       => 'default-avatar.png',
                'unit_id'    => 1,
                'alamat'     => 'Kebun Percobaan & Tefa Pengolahan Kopi Polinela',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 3,
                'nama'       => 'Admin Unit Kakao Polinela',
                'email'      => 'adminkakao@polinela.ac.id',
                'password'   => Hash::make('admin123'),
                'no_hp'      => '081234567892',
                'role'       => 'admin_unit',
                'foto'       => 'default-avatar.png',
                'unit_id'    => 2,
                'alamat'     => 'Laboratorium Pengolahan Hasil Kakao Polinela',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 4,
                'nama'       => 'Admin Unit Lada & Rempah',
                'email'      => 'adminlada@polinela.ac.id',
                'password'   => Hash::make('admin123'),
                'no_hp'      => '081234567893',
                'role'       => 'admin_unit',
                'foto'       => 'default-avatar.png',
                'unit_id'    => 3,
                'alamat'     => 'Unit Produksi Rempah Unggulan Lampung Polinela',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 8,
                'nama'       => 'Admin Unit Olahan & Atsiri',
                'email'      => 'adminatsiri@polinela.ac.id',
                'password'   => Hash::make('admin123'),
                'no_hp'      => '081234567895',
                'role'       => 'admin_unit',
                'foto'       => 'default-avatar.png',
                'unit_id'    => 4,
                'alamat'     => 'Pusat Bio-Industri & Tefa Hortikultura Polinela',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 5,
                'nama'       => 'Pimpinan Polinela',
                'email'      => 'pimpinan@polinela.ac.id',
                'password'   => Hash::make('pimpinan123'),
                'no_hp'      => '081234567894',
                'role'       => 'pimpinan',
                'foto'       => 'default-avatar.png',
                'unit_id'    => null,
                'alamat'     => 'Ruang Manajemen & Direktur Polinela',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 6,
                'nama'       => 'Budi Pratama (Civitas Polinela)',
                'email'      => 'budi@gmail.com',
                'password'   => Hash::make('konsumen123'),
                'no_hp'      => '085278901234',
                'role'       => 'konsumen',
                'foto'       => 'default-avatar.png',
                'unit_id'    => null,
                'alamat'     => 'Jl. Flamboyan Blok B No. 4, Kemiling, Bandar Lampung',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 7,
                'nama'       => 'Siti Rahmawati',
                'email'      => 'siti@gmail.com',
                'password'   => Hash::make('konsumen123'),
                'no_hp'      => '085712345678',
                'role'       => 'konsumen',
                'foto'       => 'default-avatar.png',
                'unit_id'    => null,
                'alamat'     => 'Jl. ZA Pagar Alam No. 45, Rajabasa, Bandar Lampung',
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('users')->upsert($users, ['id']);

        // 3. Categories
        $categories = [
            [
                'id'            => 1,
                'nama_kategori' => 'Kopi Nusantara Polinela',
                'slug'          => 'kopi-nusantara',
                'icon'          => 'bi-cup-hot',
                'deskripsi'     => 'Biji kopi sangrai, bubuk robusta, dan produk olahan kopi spesial dari kebun Politeknik Negeri Lampung.',
                'is_active'     => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 2,
                'nama_kategori' => 'Biji & Olahan Kakao',
                'slug'          => 'biji-olahan-kakao',
                'icon'          => 'bi-box-seam',
                'deskripsi'     => 'Kakao nibs organik, bubuk cokelat murni, serta cokelat artisan berkualitas hasil riset Tefa.',
                'is_active'     => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 3,
                'nama_kategori' => 'Rempah & Minyak Atsiri',
                'slug'          => 'rempah-minyak-atsiri',
                'icon'          => 'bi-flower1',
                'deskripsi'     => 'Lada hitam asli Lampung, minyak serai wangi murni, dan simplisia rempah perkebunan.',
                'is_active'     => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 4,
                'nama_kategori' => 'Bibit & Pupuk Perkebunan',
                'slug'          => 'bibit-pupuk-perkebunan',
                'icon'          => 'bi-tree',
                'deskripsi'     => 'Bibit tanaman perkebunan unggul bersertifikat serta pupuk organik kompos Tefa Polinela.',
                'is_active'     => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 5,
                'nama_kategori' => 'Produk Pangan Olahan Tefa',
                'slug'          => 'produk-pangan-olahan',
                'icon'          => 'bi-basket',
                'deskripsi'     => 'Produk makanan dan minuman sehat berbahan baku komoditas hasil perkebunan kampus.',
                'is_active'     => 1,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
        ];
        DB::table('categories')->upsert($categories, ['id']);

        // 4. Products
        $products = [
            [
                'id'            => 1,
                'unit_id'       => 1,
                'category_id'   => 1,
                'nama_produk'   => 'Kopi Robusta Polinela Roasted Beans 250g',
                'slug'          => 'kopi-robusta-polinela-roasted-beans-250g',
                'deskripsi'     => 'Kopi Robusta murni petik merah dari kebun percobaan Politeknik Negeri Lampung. Disangrai dengan profil medium-dark roast, menghasilkan aroma cokelat karamel yang pekat dengan crema tebal dan aftertaste manis alami.',
                'harga'         => 45000.00,
                'berat_gram'    => 250,
                'satuan'        => 'pouch',
                'stok'          => 45,
                'stok_min'      => 10,
                'gambar_utama'  => 'robusta-polinela.jpg',
                'status'        => 'aktif',
                'featured'      => 1,
                'rating_avg'    => 4.90,
                'total_terjual' => 86,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 2,
                'unit_id'       => 1,
                'category_id'   => 1,
                'nama_produk'   => 'Kopi Bubuk Robusta Organik Tefa 200g',
                'slug'          => 'kopi-bubuk-robusta-organik-tefa-200g',
                'deskripsi'     => 'Kopi bubuk halus siap seduh untuk seduhan tubruk tradisional maupun espresso. Diproses secara higienis di Tefa Pengolahan Kopi Polinela tanpa bahan pengawet atau campuran jagung.',
                'harga'         => 35000.00,
                'berat_gram'    => 200,
                'satuan'        => 'kemasan',
                'stok'          => 60,
                'stok_min'      => 10,
                'gambar_utama'  => 'kopi-bubuk.jpg',
                'status'        => 'aktif',
                'featured'      => 1,
                'rating_avg'    => 4.80,
                'total_terjual' => 120,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 3,
                'unit_id'       => 2,
                'category_id'   => 2,
                'nama_produk'   => 'Kakao Nibs Premium Fermentasi Polinela 250g',
                'slug'          => 'kakao-nibs-premium-fermentasi-250g',
                'deskripsi'     => 'Cacahan biji kakao fermentasi murni bermutu tinggi. Kaya antioksidan flavonoid, crunchy, tanpa pemanis buatan, cocok untuk cemilan sehat, topping smoothie bowl, oatmeal, dan campuran kue.',
                'harga'         => 42000.00,
                'berat_gram'    => 250,
                'satuan'        => 'jar',
                'stok'          => 35,
                'stok_min'      => 5,
                'gambar_utama'  => 'kakao-nibs.jpg',
                'status'        => 'aktif',
                'featured'      => 1,
                'rating_avg'    => 4.85,
                'total_terjual' => 54,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 4,
                'unit_id'       => 2,
                'category_id'   => 5,
                'nama_produk'   => 'Dark Chocolate Artisan Tefa 70% Single Origin 80g',
                'slug'          => 'dark-chocolate-artisan-tefa-70-persen',
                'deskripsi'     => 'Cokelat batang hitam artisan asli produksi Teaching Factory Polinela. Mengandung 70% padatan kakao lokal dengan rasa fruity nutty yang elegan, meleleh sempurna di lidah.',
                'harga'         => 28000.00,
                'berat_gram'    => 80,
                'satuan'        => 'batang',
                'stok'          => 50,
                'stok_min'      => 8,
                'gambar_utama'  => 'dark-chocolate.jpg',
                'status'        => 'aktif',
                'featured'      => 1,
                'rating_avg'    => 4.95,
                'total_terjual' => 92,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 5,
                'unit_id'       => 3,
                'category_id'   => 3,
                'nama_produk'   => 'Lada Hitam Lampung Asli (Black Pepper) Butir 200g',
                'slug'          => 'lada-hitam-lampung-asli-butir-200g',
                'deskripsi'     => 'Lada hitam asli Lampung yang terkenal di dunia internasional dengan aroma pedas menyengat dan minyak atsiri piperin tinggi. Dikeringkan alami dengan kadar air terkontrol.',
                'harga'         => 38000.00,
                'berat_gram'    => 200,
                'satuan'        => 'pouch',
                'stok'          => 40,
                'stok_min'      => 10,
                'gambar_utama'  => 'lada-hitam.jpg',
                'status'        => 'aktif',
                'featured'      => 1,
                'rating_avg'    => 4.90,
                'total_terjual' => 67,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 6,
                'unit_id'       => 4,
                'category_id'   => 3,
                'nama_produk'   => 'Minyak Atsiri Serai Wangi (Citronella Oil) Murni 100ml',
                'slug'          => 'minyak-atsiri-serai-wangi-murni-100ml',
                'deskripsi'     => 'Minyak atsiri serai wangi hasil distilasi uap daun segar di Tefa Polinela. 100% murni tanpa pelarut, wangi segar relaksasi, efektif sebagai pengusir nyamuk alami dan aromaterapi.',
                'harga'         => 55000.00,
                'berat_gram'    => 150,
                'satuan'        => 'botol',
                'stok'          => 25,
                'stok_min'      => 5,
                'gambar_utama'  => 'minyak-atsiri.jpg',
                'status'        => 'aktif',
                'featured'      => 1,
                'rating_avg'    => 4.75,
                'total_terjual' => 38,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 7,
                'unit_id'       => 4,
                'category_id'   => 4,
                'nama_produk'   => 'Pupuk Kompos Organik Hayati Tefa Agro 5kg',
                'slug'          => 'pupuk-kompos-organik-hayati-tefa-5kg',
                'deskripsi'     => 'Pupuk kompos terfermentasi bakteri selulolitik dari limbah tanaman perkebunan dan kotoran ternak riset. Menyuburkan tanah, memperbaiki aerasi akar, dan ramah lingkungan.',
                'harga'         => 25000.00,
                'berat_gram'    => 5000,
                'satuan'        => 'karung',
                'stok'          => 80,
                'stok_min'      => 15,
                'gambar_utama'  => 'pupuk-organik.jpg',
                'status'        => 'aktif',
                'featured'      => 0,
                'rating_avg'    => 4.80,
                'total_terjual' => 45,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'id'            => 8,
                'unit_id'       => 4,
                'category_id'   => 4,
                'nama_produk'   => 'Bibit Kopi Robusta Unggul Klon BP 308 Polinela',
                'slug'          => 'bibit-kopi-robusta-klon-bp-308',
                'deskripsi'     => 'Bibit kopi robusta unggul klon rekomendasi hasil perbanyakan setek dan okulasi di Kebun Induk Polinela. Tahan penyakit karat daun dan berbuah lebat.',
                'harga'         => 15000.00,
                'berat_gram'    => 1000,
                'satuan'        => 'polybag',
                'stok'          => 100,
                'stok_min'      => 20,
                'gambar_utama'  => 'bibit-kopi.jpg',
                'status'        => 'aktif',
                'featured'      => 0,
                'rating_avg'    => 5.00,
                'total_terjual' => 110,
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
        ];
        DB::table('products')->upsert($products, ['id']);

        // 5. Initial Stocks
        $stocks = [];
        foreach ($products as $p) {
            $stocks[] = [
                'product_id'    => $p['id'],
                'tipe'          => 'masuk',
                'jumlah'        => $p['stok'],
                'stok_sebelum'  => 0,
                'stok_sesudah'  => $p['stok'],
                'keterangan'    => 'Stok awal sistem panen raya',
                'user_id'       => 1,
                'created_at'    => now(),
            ];
        }
        DB::table('stocks')->insert($stocks);

        // 6. Vouchers
        $vouchers = [
            [
                'id'           => 1,
                'kode'         => 'POLINELAJUARA',
                'nama'         => 'Diskon Civitas Polinela Juara',
                'tipe'         => 'fixed',
                'diskon'       => 20000.00,
                'min_belanja'  => 50000.00,
                'max_diskon'   => 20000.00,
                'kuota'        => 200,
                'terpakai'     => 12,
                'tgl_mulai'    => '2026-01-01',
                'tgl_berakhir' => '2026-12-31',
                'is_active'    => 1,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 2,
                'kode'         => 'PANENRAYA10',
                'nama'         => 'Promo Panen Raya 10%',
                'tipe'         => 'persen',
                'diskon'       => 10.00,
                'min_belanja'  => 30000.00,
                'max_diskon'   => 25000.00,
                'kuota'        => 150,
                'terpakai'     => 28,
                'tgl_mulai'    => '2026-01-01',
                'tgl_berakhir' => '2026-12-31',
                'is_active'    => 1,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'id'           => 3,
                'kode'         => 'MAHASISWAAGRO',
                'nama'         => 'Subsidi Belanja Praktikum Mahasiswa',
                'tipe'         => 'fixed',
                'diskon'       => 15000.00,
                'min_belanja'  => 40000.00,
                'max_diskon'   => 15000.00,
                'kuota'        => 100,
                'terpakai'     => 5,
                'tgl_mulai'    => '2026-01-01',
                'tgl_berakhir' => '2026-12-31',
                'is_active'    => 1,
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
        ];
        DB::table('vouchers')->upsert($vouchers, ['id']);

        // 7. Banners
        $banners = [
            [
                'id'         => 1,
                'judul'      => 'Panen Raya Kopi Robusta & Kakao Polinela',
                'subjudul'   => 'Nikmati cita rasa kopi petik merah dan produk olahan kakao asli kebun riset kampus vokasi terbaik Lampung.',
                'gambar'     => 'banner-kopi.jpg',
                'link'       => 'katalog',
                'urutan'     => 1,
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id'         => 2,
                'judul'      => 'Lada Hitam Lampung & Minyak Atsiri Alami',
                'subjudul'   => 'Rempah aromatik berkualitas ekspor dan ekstrak serai wangi hasil produksi Teaching Factory Polinela.',
                'gambar'     => 'banner-rempah.jpg',
                'link'       => 'katalog?kategori=rempah-atsiri',
                'urutan'     => 2,
                'is_active'  => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('banners')->upsert($banners, ['id']);
    }
}
